### ISSUE TITLE
\n in mo.md literally interperted in markdown mode

### ISSUE THREAD

**Issue by dmadisetti** [marimo-team/marimo#1004]
### Describe the bug

Clicking on the markdown mode cell button transforms the literal `\n` to a breakline

![image](https://github.com/marimo-team/marimo/assets/2689338/dc74652a-122f-4564-a303-0ea3f4565877)
![image](https://github.com/marimo-team/marimo/assets/2689338/29e4201f-200e-4f5b-b507-83c7876af55d)

changing back

![image](https://github.com/marimo-team/marimo/assets/2689338/1a8edef0-7195-4af9-8dec-c08a3e37e4ea)

### Environment

0.3.4

### Code to reproduce

```python
mo.md(
    r"""
    Some people denote Poisson's ratio as $n$, $\nu$, or even $\mathllap{}\cdot\mathllap{\alpha}$
    """
)
```
Breaks on the \nu

try it here:
https://marimo.app/l/z5epex

**Comment by fuenfundachtzig** [comment]
The problem seems to be caused by [this line](https://github.com/dmnd/dedent/blob/e634f0e59279796e9bb1019836593cde22ab5835/src/dedent.ts#L76) at the end of the dedent function itself.

![image](https://github.com/marimo-team/marimo/assets/8006302/48a5b761-f3f7-4dc2-abfc-1eb221d546a5)

#1038 proposes to switch to dedent-js which doesn't have this problem.
