### ISSUE TITLE
Reactive reloading

### ISSUE THREAD

**Issue by MartinBernstorff** [marimo-team/marimo#1101]
### Description

On the heels of #1092, I'd love to have reactive reloading.

### Suggested solution

When a file which is imported into marimo changes on disk, mark the affected cells as stale.

**Comment by akshayka** [comment]
@MartinBernstorff , just merged! Setting the autoreload config to `detect` implements your suggested form of reacting reloading: cells are marked stale but not automatically run

As a bonus, we added one more option. Setting the config to `autorun` makes it fully reactive: on save, modified cells are automatically run.

This will be released in the next version of marimo.

cc @astrowonk, @dmadisetti , since I know you all were also interested in this.

**Comment by astrowonk** [comment]
> @MartinBernstorff , just merged! Setting the autoreload config to `detect` implements your suggested form of reacting reloading: cells are marked stale but not automatically run
> 
> As a bonus, we added one more option. Setting the config to `autorun` makes it fully reactive: on save, modified cells are automatically run.
> 
> This will be released in the next version of marimo.
> 
> cc @astrowonk, @dmadisetti , since I know you all were also interested in this.

I remain impressed at the speed at which you all are iterating on Marimo. Thanks!

**Comment by MartinBernstorff** [comment]
Incredible pace, super excited to try it out!
