### ISSUE TITLE
Provide non-Marimo command-line arguments to app

### ISSUE THREAD

**Issue by twrightsman** [marimo-team/marimo#1137]
### Description

Access a filtered list of command-line arguments that were not used by Marimo, mostly to configure notebooks running as scripts.

### Suggested solution

Provide some API, e.g. `mo.args()`, similar to `mo.query_params()`, that returns a list of arguments that Marimo didn't use to configure itself. Perhaps a separator like `--` could explicitly separate Marimo from non-Marimo arguments.

This list could then be parsed with normal `argparse` like `parser.parse_args(args = mo.args())`.

### Alternative

`sys.argv` is definitely accessible, but contains a mixture of Marimo and non-Marimo (if provided) arguments and filtering these in the notebook would break as Marimo's API changes.

**Comment by dmadisetti** [comment]
+1
I think it'd be ideal if query_params and args shared the command

**Comment by mscolnick** [comment]
I sketched this out a bit a while back. I didn't want to combine the two implicitly because the author can control the CLI args, while the user can control the query-params, and by default it would be nice to keep those permissions separate. Also the casing can be different based on typical usage (kebab for CLI and various for query-params). Also it's hard to pick one when they conflict

So instead, I wanted to add a util that can wrap and combine these smartly, with validation.

```python
arg = mo.cli_args() # just the args, plain
query_params = mo.quey_params() # just the query params, plain

combined = mo.args([
     mo.cli_args(),
     mo.quey_params(), # query-params will overwrite any cli args
], casing="kebab")

# validated
combined = mo.args([
     mo.cli_args(),
     mo.quey_params(),
], casing="kebab", validate=PydanticModel]
```

**Comment by twrightsman** [comment]
Thank you @mscolnick! Looking forward to testing
