### ISSUE TITLE
Marimo auto-markdown view modifies original code

### ISSUE THREAD

**Issue by delennc** [marimo-team/marimo#1486]
### Describe the bug

My cell with `mo.md` got automatically turned into a markdown cell, and when I turned it back into python it lost the formatting.

Original input:

```
mo.md(f"""
Hello
""")
```

Code in the cell after transformed back to python from the markdown cell:

```
mo.md(f"Hello")
```

### Environment

0.6.6

### Code to reproduce

```
mo.md(f"""
Hello
""")
```

**Comment by delennc** [comment]
Also it was confusing that it randomly turned into a markdown cell when I had created a python cell

**Comment by akshayka** [comment]
> My cell with mo.md got automatically turned into a markdown cell, and when I turned it back into python it lost the formatting.

This is a bug that we should fix (good first issue!) — viewing a cell's code as markdown should _never_ change the notebook code.

>  Also it was confusing that it randomly turned into a markdown cell when I had created a python cell

This is a design choice we are experimenting with — rendering cells that have a single `mo.md()` expression as markdown on notebook startup. I can see how this can be confusing, though ...

**Comment by metaboulie** [comment]
get this ☑️

**Comment by mscolnick** [comment]
Closing as wont-fix. 

When actively convert single quote markdown to triple quote (and properly add new lines if needed). We do this in order to prevent bugs with latex and quote escaping. This is a deliberate choice in order to avoid other more blocking issues (e.g. incorrect escaping or latex doesn't work).

See https://github.com/marimo-team/marimo/pull/1857
