### ISSUE TITLE
The iframe element only supports the marimo.app

### ISSUE THREAD

**Issue by wwj718** [marimo-team/marimo#1489]
### Describe the bug

I can open https://marimo.app/l/aojjhb?embed=true using iframe in marimo.new, but cannot open any other url except marimo.app

This online notebook demonstrates the problem : https://marimo.app/l/hgb5vm

### Environment

marimo.new (WASM)

### Code to reproduce

This online notebook demonstrates the problem : https://marimo.app/l/hgb5vm

**Comment by mscolnick** [comment]
This is actually a security issue. In order to run our playground (marimo.app) effectively with wasm, we enable some security flags on the top-level document. Specifically, `cross-origin-embedder-policy` and `cross-origin-opener-policy`.

If you want to embed an iframe, you must be in control of the sever serving the iframe's contents and similarly add the `Cross-Origin-Resource-Policy` header. For example,
`Cross-Origin-Resource-Policy: cross-origin` if the resource is served from another location than your website. If you set this header, any website can embed this resource.

**Comment by wwj718** [comment]
Thank you for the explanation, 

> you must be in control of the sever serving the iframe's contents and similarly add the Cross-Origin-Resource-Policy header

I added the following content and restarted nginx, but it didn't seem to take effect.

```
add_header Cross-Origin-Resource-Policy cross-origin always;
add_header Cross-Origin-Embedder-Policy unsafe-none always;
```

<img width="787" alt="image" src="https://github.com/marimo-team/marimo/assets/3153878/7d931ab3-dcf5-40f2-9b3c-0bc56cc154bb">

**Comment by mscolnick** [comment]
Can you share a link with me so I can verify the correct headers are set? If you'd prefer, you can DM me on discord https://marimo.io/discord

**Comment by wwj718** [comment]
Sure! Here is the link:  https://snap.codelab.club/snap.html

Here is the current nginx headers:

```
    add_header Cross-Origin-Resource-Policy cross-origin;
    add_header Cross-Origin-Resource-Policy credentialless;
```

**Comment by mscolnick** [comment]
Going to close this, please re-open if you are blocked.
