### ISSUE TITLE
disabled cell variable definition remains active

### ISSUE THREAD

**Issue by ggggggggg** [marimo-team/marimo#1967]
### Describe the bug

I made a cell that defined a variable `a`, then decided I wanted to try a different definition while keeping the first around. I disabled that cell and made a new cell that defines the variable `a`. The new cell has an error because of the first cell. I expected the first cell to have no effect on the evaluation of the notebook since it is disabled.

### Environment

{
  "marimo": "0.7.17",
  "OS": "Windows",
  "OS Version": "10",
  "Processor": "Intel64 Family 6 Model 85 Stepping 4, GenuineIntel",
  "Python Version": "3.10.11",
  "Binaries": {
    "Browser": "126.0.6478.127",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.0",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.16.1",
    "tomlkit": "0.12.5",
    "uvicorn": "0.30.1",
    "starlette": "0.37.2",
    "websockets": "12.0",
    "typing-extensions": "4.7.1",
    "ruff": "0.5.5"
  }
}

### Code to reproduce

```python
import marimo

__generated_with = "0.7.17"
app = marimo.App(width="medium")


@app.cell(disabled=True)
def __():
    a = 4
    return a,


@app.cell
def __():
    a = 5
    return a,


@app.cell
def __():
    return


if __name__ == "__main__":
    app.run()
```

**Comment by akshayka** [comment]
This is actually intentional.

Disabling a cell doesn't remove it from marimo's internal graph, nor does it remove the cell's variables from memory. The main use case that at least I thought of was to allow you to iterate on "earlier" parts of a notebook without triggering execution of a later parts, as described [in the docs](https://docs.marimo.io/guides/reactivity.html#disabling-cells). When you're ready, you can re-enable the cell and your notebook will be made up-to-date.

1. Perhaps the documentation could be clearer.
2. Perhaps the word "disable" is not quite right. Maybe "pause" would be better?
3. To confirm: you would like an option to remove a cell from marimo's graph, and remove its variables from memory, while still keeping the code in your notebook. Is that correct?

**Comment by akshayka** [comment]
> To confirm: you would like an option to remove a cell from marimo's graph, and remove its variables from memory, while still keeping the code in your notebook. Is that correct?

If this is indeed the case (and apologies if I have misunderstood), I have a couple of suggestions:

1. Temporarily wrap the code that you want to "disable" in a function:

```python
def _():
  # disabled code here
  ...
```

2. Try using the scratchpad panel, which gives you a single-cell REPL that is allowed to redefine variables. Perhaps this works for your use case, perhaps it doesn't.

**Comment by ggggggggg** [comment]
I don't feel strongly that this behavior needs to change, so I agree this is more of a naming/documentation issue. To me `disable` means it's like it's not there. I think it should be called `autorun`, which is already used in the settings pane to describe identical (or maybe only very similar) behaviors. Part of why I thought it would remove it from the graph is that it was a different name from `autorun`, so clearly it must have different intention.

**Comment by akshayka** [comment]
Thanks for writing back. I will think about improving the naming.
