### ISSUE TITLE
support checking undefined name usage before running a cell

### ISSUE THREAD

**Issue by Oreoxmt** [marimo-team/marimo#2051]
### Description

I notice that undefined name usage is now a runtime exception:

<img width="560" alt="image" src="https://github.com/user-attachments/assets/5833fc69-8e22-4e2e-aba7-e6d766213065">

But marimo can actually check for errors like multiple definitions and cyclic dependencies before a cell is run:

<img width="444" alt="image" src="https://github.com/user-attachments/assets/acee02bb-687d-496d-ab00-bdd0bec64682">

I think marimo already knows the dependency graph and is able to check for this kind of error in static analysis as well.

### Suggested solution

Add an undefined name usage check in the following function:

https://github.com/marimo-team/marimo/blob/beccc28ccada25923bcf897a80a8c1e028c51adc/marimo/_runtime/validate_graph.py#L76-L87

**Comment by dmadisetti** [comment]
This is already solved if you use `strict` mode which also prevents mutations. This isn't enforced otherwise, since this is a bit more of a burden.

Strict mode is still experimental but can be turned one with:

```python
[experimental]
execution_type = "strict"
```

A big caveat of strict mode, is that it does do copies behind the scenes which could potentially slow things down. I don't know of anyone using strict mode except for me (please LMK if someone does!). I think it might be reasonable to turn the forced copies to copy-on-write but I think that might need more interest than just me

**Comment by Oreoxmt** [comment]
This is exactly what I want. I think it's ok for me to use it as an experimental feature for now. Thanks very much!
