### ISSUE TITLE
add move to cell above/below option in the cell menu

### ISSUE THREAD

**Issue by metaboulie** [marimo-team/marimo#2229]
### Description

<img width="301" alt="Screenshot 2024-09-05 at 16 43 26" src="https://github.com/user-attachments/assets/c5a70a88-6631-4576-9b6f-a2339fd3ad80">

### Suggested solution

In the cell menu, add 2 options, move to cell above and move to cell below,
enter the other cell's name and move the current cell to corresponding position.

**Comment by mscolnick** [comment]
This is an interesting idea. most cells don't have names and i am not sure how often people name them today. 

**Alternative:**
We could also allow this for headers maybe: `Move to section` and we list h1s and/or h2s. And rather than typing the name, we just put all H1/H2s in a submenu. We would need to figure out a mapping of section back to the cell (which we probably have in some way)
