### ISSUE TITLE
Support hiding output with mo.sql (with a 'Show Output' toggle)

### ISSUE THREAD

**Issue by ben-pr-p** [marimo-team/marimo#2266]
### Describe the bug

For `mo.md`, `mo.ui.*`, etc., the result is only sent to the output if it's the implicit/explicit return. For `mo.sql`, it's appended to the output no matter where 

In this example:
```python
my_query = mo.sql(
    f"""
    select * from people
    """
)
```
Output is still rendered, even though my_query is not returned.

In order to suppress it, I have to do:
```python
my_query = mo.sql(
    f"""
    select * from people
    """
)

"Ignore" # some return string to silence mo.sql's output
```

Which feels like a hack.

I would like to use SQL cells for data transformations, and often / usually don't want to visualize the output directly.

I think `mo.sql`'s behavior should work like other `mo.*` things, and the SQL cell should by default map to:
```python
my_query = mo.sql("select * from people")
my_query
```
So that output is shown, and then a toggle on the cell can exist to hide the output (which removes the final my_query return without translating the cell to Python).

### Environment

```
{
  "marimo": "0.7.12",
  "OS": "Darwin",
  "OS Version": "23.6.0",
  "Processor": "arm",
  "Python Version": "3.12.4",
  "Binaries": {
    "Browser": "119.0.6045.123",
    "Node": "v18.17.0"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.9",
    "pygments": "2.18.0",
    "tomlkit": "0.13.0",
    "uvicorn": "0.30.3",
    "starlette": "0.38.2",
    "websockets": "12.0",
    "typing-extensions": "4.12.2",
    "ruff": "0.5.5"
  }
}
```

### Code to reproduce

N/A, provided above

**Comment by mscolnick** [comment]
This is a fair callout and we can improve this. Couple background points:

* while you can of course us `mo.sql`, manually, it was meant be used as part of the SQL cells which looks like SQL but writes to Python
* because of this, we wanted to keep make the translations from python<>sql as minimal as possible. one way to do this was to avoid a return type, and instead have `mo.sql` use `mo.ouput.replace` under the hood. this allows us to easily optimize  the output (i.e. change the table config) without effecting the result. this also allows us to display a table, but while returning a polars/pandas dataframe

I can totally see how this is a different pattern compared. Would any of these changes make the ergonomics better?

1. draw dependencies between tables/schemas in `duckdb.sql` like we do with `mo.sql`. This way you can use `duckdb.sql` and still get the reactive benefits without the [extra output we do under the hood](https://github.com/marimo-team/marimo/blob/07c59347a0330effca4ae1ea98722971e81b3ea8/marimo/_sql/sql.py).
2. we could provide an argument for `mo.sql(output=True | False)`, which would allow you to write SQL without displaying a result

**Comment by ben-pr-p** [comment]
Totally understand the design considerations - makes sense! 

I think both of those changes would be great, but my concern is that neither would provide support for hiding output without flipping the cell to Python. If possible, I'd like to keep it as a SQL cell for the syntax highlighting benefits.

I think:
- Adding a "Show Output: [x]" toggle to the SQL cell UI (default checked)
- Mapping that to `mo.sql("query", output=True | False)`

I would think 1 is useful for direct manipulation of attached and persisted DuckDB databases (is that supported with `mo.sql`?), and less this use case.

**Comment by ben-pr-p** [comment]
Thanks so much! Loving the DX of the SQL cells :)
