### ISSUE TITLE
Markdown cells, code cells, and smart cells: taking inspiration from Livebook

### ISSUE THREAD

**Issue by patrick-kidger** [marimo-team/marimo#2313]
### Description

Right now, Marimo has essentially two kinds of cell: code cells and Markdown cells. (Although I do appreciate that Markdown cells are secretly just code cells featuring only a `mo.md` call.) Markdown cells are pretty straightforward, but code cells live a kind of double life: sometimes they're about building a UI application via `marimo.ui.*` and friends. Sometimes they're about displaying the actual code itself!

Right now we have to make a global choice about which of these two things is most important, across the entire notebook, based on whether we `--include-code` or not.

I'm proposing to take inspiration from [Livebook](https://livebook.dev) (from the Elixir/Erlang community), which acknowledges this difference by explicitly having three kinds of cell: Markdown cells, code cells, and 'smart' cells, the last of which are mini programmatic UIs wrapping a code cell -- that is, exactly like what Marimo provides. And most importantly... all three of these cells types can be mix-and-match'd in any way.

i'd love to have that approach in Marimo as well.

(In fact Livebook seems to have quite a lot of nice ideas floating around in it, so I suspect there may be other points worth taking inspiration from it as well.)

### Suggested solution

-

**Comment by akshayka** [comment]
If the point of having multiple kinds of cells is to alleviate

> Right now we have to make a global choice about which of these two things is most important, across the entire notebook, based on whether we --include-code or not.

would you be satisfied if we simply added a "pin" configuration to cells, so that a pinned cell's code is always shown in the app view? As we've discussed in https://github.com/marimo-team/marimo/issues/2038.

I personally enjoy the fact that in marimo, there's only one kind of cell, i.e. Python; that was an intentional decision. Like you've mentioned, markdown "cells" are just UI sugar that we added later on for the basic use case when one would like to write text without interpolation of Python values.

I just downloaded Livebook and played with it, and it seems like "Smart cells" are also just UI sugar? I personally don't see the benefit they provide, but perhaps I haven't used it long enough.

**Comment by patrick-kidger** [comment]
> would you be satisfied if we simply added a "pin" configuration to cells, so that a pinned cell's code is always shown in the app view? As we've discussed in #2038.

I think that might be starting to get a little hairy: in the 'code' view we would have:

- markdown cells, for which their code is hidden
- pinned code cells, for which their code is visible
- unpinned code cells, for which their code is visible
- smart cells (what does Marimo call cells that use `marimo.ui.etc`?), fo which their code is visible

whilst in the App `--no-include-code` view, we would have:

- markdown cells, for which their code is hidden
- pinned code cells, for which their code is visible
- unpinned code cells, for which their code is hidden
- smart cells, for which their code is hidden

and in the App `--include-code` view, we would have:

- markdown cells, for which their code is hidden (as of #2286)
- pinned code cells, for which their code is visible
- unpinned code cells, for which their code is visible
- smart cells, for which their code is visible

That's a pretty complicated mish-mash of when something is visible vs when something is hidden! I probably couldn't teach that to a new user very easily.

Perhaps there should be just two kinds of view: code view, in which every kind of cell has their underlying Python code visible (including Markdown cells). Then the App view (remove the existence of the `--include-code` flag), for which markdown cells display only their markdown, pinned cells display their code, unpinned cells vanish, and smart cells show their UI.

**Comment by dmadisetti** [comment]
I haven't touch Quarto exports in awhile- trying to build out precomputing values to make them more usable-

However, cell level annotation specific to export are supported by this implementation: https://dmadisetti.github.io/quarto-marimo (not working right now, but the spec we'll start from again)

**Comment by akshayka** [comment]
> smart cells (what does Marimo call cells that use marimo.ui.etc?), fo which their code is visible

marimo has just one type of cell: Python. Cells that don't use `mo.ui` can also have outputs. There's nothing privileged about cells that use `marimo.ui`.

> That's a pretty complicated mish-mash of when something is visible vs when something is hidden!

I think it can be explained simply.

"Code view", i.e. `marimo edit`:
- Each cell's code is visible.

"App view", i.e. `marimo run`:
- Each cell's code is hidden unless it is pinned.

"App view" with `--include-code`, i.e. `marimo run --include-code`:
- The same as `marimo run`, except we include a button that toggles between the `marimo run` view and the `marimo edit` view. 

The last option, `--include-code`, is useful when deploying notebooks as examples on the public web ([example](https://marimo.io/@public/signal-decomposition)), and you want the reader to be able to see the entire notebook's code for educational purposes.

**Comment by mruoss** [comment]
> I just downloaded Livebook and played with it, and it seems like "Smart cells" are also just UI sugar? I personally don't see the benefit they provide, but perhaps I haven't used it long enough.

Just a quick explanation on Smart cells from an Elixir dev. Smart cells are UI sugar for code generation. They are great to get people started on a library they don't know yet. They give you a nice UI to get a working prototype. You can then switch the UI to the generated code and use that in your application. 

The following video demonstrates this. [explorer](https://hexdocs.pm/explorer/Explorer.html) is a data exploration library working with dataframes. [kino_explorer](https://hexdocs.pm/kino_explorer/components.html) is the library bringing a nice UI to livebook that lets you create a data processing pipeline. You can then look at the generated code or convert the UI sugar to a code cell.

https://github.com/user-attachments/assets/02283337-75aa-4657-8379-071c25e90210

**Comment by akshayka** [comment]
Thanks for the video! That's a very clear demonstration, thank you. We have a [similar component for transforming dataframes](https://docs.marimo.io/guides/dataframes.html#transforming-dataframes), that also supports code generation.

I suppose one difference is that our components are created programmatically instead of via the UI, which lets users display them using custom layouts, build higher-order components, etc.

**Comment by mruoss** [comment]
You're welcome. Just one side note (not sure it was clear in my last comment): `kino_explorer` is just one example for a smart cell. There are many others (e.g. [`kino_k8s`](https://x.com/miruoss/status/1719096634166898720) which lets you generate code for working with the Kubernetes API, `kino_db` for working with databases, and many more)

**Comment by VivaldoMendes** [comment]
Hi @patrick-kidger, @akshayka. In a previous issue [2038](https://github.com/marimo-team/marimo/issues/2038), I tried to draw attention to the potential limitations of a crucial lack of flexibility regarding **_hiding/displaying_** code in the notebook's App view. To make the argument as simple as possible, I elaborated on what occurs in Hex notebooks, where making the code visible in both the notebook view and the App view is a choice made possible on a **_cell-by-cell basis_**. I mentioned the Hex case because it is also a Python notebook and one that gives special attention to the App view as far as I can extrapolate. However, I would like to stress that this functionality is available in **_all notebooks_** that the community has widely used: Jupyter, Pluto, and Observable.

Indeed, for the writer of a particular notebook, that choice (hide/display input code in a discretionary manner) is not crucial (possibly irrelevant) because he or she writes and uses the notebook. He/she is the only user of the notebook!  But if the notebook is written for somebody else to use or read, the possibility of choosing which cells have their code visible in the App view (or in the notebook view) and which ones should have their code hidden is critical.

I use notebooks extensively in teaching (Pluto.jl and Julia). If the abovementioned option is not available, it will not be possible for me to consider using marimo for the same task. In teaching/education, the writer needs considerable flexibility about what is displayed/hidden in the notebook and the App view. The point is simple: all available notebooks that are widely used have implemented that functionality because they have it to their advantage. If Mariamo does not implement it, I believe this fantastic piece of software will not achieve its full potential.

---

Ps. I have just received the marimo's Newsletter 6. It is lovely to see a new functionality in marimo: sandboxed notebooks. As mentioned in the newsletter, this replicates a fundamental characteristic of Pluto notebooks in Julia: a package environment built inside each notebook. I am a Julia and Pluto user and know by experience how important that characteristic is for teaching because the only package students have to install is Pluto ... and notebooks always run smoothly. However strange it may seem, for using notebooks in teaching, the hide/display code is even more important from a practical point of view.

**Comment by akshayka** [comment]
Thanks @VivaldoMendes for explaining so clearly why this feature matters to you.

> But if the notebook is written for somebody else to use or read, the possibility of choosing which cells have their code visible in the App view (or in the notebook view) and which ones should have their code hidden is critic

_Regarding this point, as you have pointed out, what we are missing today is controlling which cells have their code visible in the app view, and we can definitely design a feature that enables this._

Unless I am misunderstanding something, we do currently allow configuration of which cells have their code visible or hidden in the `edit` view. For example, in the below screenshot (edit view), we see two cells: one with the code hidden, and one with code visible:

![image](https://github.com/user-attachments/assets/e4d46688-6b4f-4cbb-9ae3-824cdf5f2573)

This per-cell hiding is similar to what Pluto.jl and Observable implement (please correct me if I am wrong!), and is configurable in the cell action menu: 

![image](https://github.com/user-attachments/assets/3f81e407-cf3b-49e4-b1c7-997ddb1a566c)

**Comment by VivaldoMendes** [comment]
Hi @akshayka. Yes, you are right: in the edit view (what I call the notebook view in the note above), we can decide on a discretionary basis which cells have the input code displayed and which do not. And this is indeed extremely relevant. 

I may have given a wrong impression in my note, but I wanted to stress that such importance/relevance remains as valid in the App view as in the edit view.  I understand that with so many demands and specific needs that I have seen in this forum, it seems complicated for the dev team to answer or consider all of them. I am a user and pay nothing for the fantastic software marimo's team has developed. I am just trying to help, giving back my two cents. Thanks.

**Comment by akshayka** [comment]
>  but I wanted to stress that such importance/relevance remains as valid in the App view as in the edit view.

Understood -- we'll get this done. Thanks for your patience!

**Comment by akshayka** [comment]
I know this issue has smart cells in its title, but I think it was really about controlling whether code is shown on a per-cell basis in the presentation view of a marimo notebook. This is now possible via `mo.show_code()`: 

See the docs for more information: https://docs.marimo.io/api/outputs.html#display-cell-code-in-marimo-s-app-views

In particular, regarding

> I think my only strong opinion is that I'd like to see `--include-code` be removed entirely, in favour of something at the per-cell level.

with `mo.show_code()`, you can choose to include code on a per-cell basis without using the `--include-code` flag.

**Comment by VivaldoMendes** [comment]
Wonderful. This small but critically important feature substantially increased the number of potential users of marimo.

**Comment by akshayka** [comment]
> Wonderful. This small but critically important feature substantially increased the number of potential users of marimo.

Fantastic! I hope it solves your use case. If it doesn't, let us know.

**Comment by VivaldoMendes** [comment]
I played a bit with this new functionality. It increases the flexibility of editing the notebooks and will undoubtedly be a handy tool. However, an aspect of the solution presented deserves some improvement. I will be sharing two images below that show my points.

The first is that, in the edit view, the cells with the input (code) visible in the App view will have their code repeated. In the case of cells with no direct output, overlapping the two sets of code (original code and the code that will be visible in the App view) looks complicated because it reduces the notebook's readability. Please take a look at the first image below.

Second, in the edit view, cells that produce a direct output still have a readability problem because we have a piece of code **_below_** the output (that is, the original code input) and the same code **_above_** the output (the code that will be visible in the App view). Please see the second image. This may bring up another point that may confuse users: in the edit view, the input code is presented below its output, while it appears above its output in the App view.

I wonder if it is not possible to _avoid displaying the code that will appear in the App view_ ... in the edit view. We do not need to see it in the edit view at all.

---

![a](https://github.com/user-attachments/assets/30e2f7f8-cc8a-4742-ba50-60641c1a52f9)

---

![aa](https://github.com/user-attachments/assets/3960fe12-3062-4926-968f-4762089a765b)

**Comment by akshayka** [comment]
For the position of the code relative to the output, we can readily switch it to match edit view (output above, code below). That is no problem.

For the repeated code in edit view, I think that is a small cost to pay for a sensible programmatic solution that works directly within the rules of marimo - the last expression of a cell is its output. We are trying to minimize configuration driven features as much as possible, as these make the implementation substantially more complex while also complicating the notebook UI. So we likely will not change this aspect of the user interface anytime soon.

In the meantime, if there is code that should be shown in the app view, perhaps you can hide it in the edit view to make working with the notebook more ergonomic. After all this is what our users do with markdown already.

**Comment by VivaldoMendes** [comment]
I understand. It's OK. As it stands now, it is better than it was without the possibility to choose which code would be visible in the App view. However, for students to use the notebook, I think it will look a little confusing that to avoid the duplication of code in the edit view, we have to hide the "active" code while the "passive" version will be visible. 

But as you mentioned, given the overall architecture of marimo, this is the small cost we must bear. For my personal use, marimo is excellent as it stands right now.
