### ISSUE TITLE
sidebar order of cells not deterministic

### ISSUE THREAD

**Issue by alefminus** [marimo-team/marimo#2343]
### Describe the bug

In a notebook with two cells using mo.sidebar, breaking the first cell (by introducing unparsable content, as would happen by accident in a normal development session), then rerunning the first cell results in it's output now being below the second cell's

### Environment

```
❯ uvx marimo env
{
  "marimo": "0.8.15",
  "OS": "Linux",
  "OS Version": "6.10.9-200.fc40.x86_64",
  "Processor": "",
  "Python Version": "3.12.6",
  "Binaries": {
    "Browser": "--",
    "Node": "v20.12.2"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.9",
    "ruff": "0.6.5",
    "starlette": "0.38.5",
    "tomlkit": "0.13.2",
    "typing-extensions": "missing",
    "uvicorn": "0.30.6",
    "websockets": "12.0"
  },
  "Optional Dependencies": {}
}
```

### Code to reproduce

```python
import marimo

__generated_with = "0.8.15"
app = marimo.App(width="medium")


@app.cell
def __():
    import marimo as mo
    return mo,


@app.cell
def __(mo):
    mo.sidebar(1)
    # now edit the above line to be "bug. mo.sidebar(1)" and run it
    # then edit it to be correct; the location in the sidebar will now be inverted.
    return


@app.cell
def __(mo):
    mo.sidebar(2)
    return


@app.cell
def __():
    return


if __name__ == "__main__":
    app.run()
```

# Initial
![Screenshot from 2024-09-18 10-19-14](https://github.com/user-attachments/assets/bc635105-05bf-4b07-9159-8d9738ca7d2f)

# After error
![Screenshot from 2024-09-18 10-19-20](https://github.com/user-attachments/assets/4992e3ff-bddb-411a-b4c0-2bd75ea228cb)

# Fixed and inverted
![Screenshot from 2024-09-18 10-19-24](https://github.com/user-attachments/assets/962a2e9c-2a7a-4227-8477-36cd9a21cb58)

**Comment by mscolnick** [comment]
@alefminus, we take into account the order in which they appear in the DAG. Since these are siblings, they don't have a relative order to one another and you would need to force one. Notebook order is not an API that we want to adhere to since in future we may run cells in parallel or other optimizations. 

Separately, I would use `mo.sidebar` **once**, and not multiple times. You can use it more than once time, but would use so sparingly and only if needed. `mo.sidebar` in the example takes in an array and will `hstack` the items for you. You can also pass in a `footer`.


```
mo.sidebar(
        [
            mo.md("# marimo"),
            mo.nav_menu(
                {
                    "#home": f"{mo.icon('lucide:home')} Home",
                    "#about": f"{mo.icon('lucide:user')} About",
                    "#contact": f"{mo.icon('lucide:phone')} Contact",
                    "Links": {
                        "https://twitter.com/marimo_io": "Twitter",
                        "https://github.com/marimo-team/marimo": "GitHub",
                    },
                },
                orientation="vertical",
            ),
        ]
    )
```

I am going to close this as wont-fix, thank you for the detailed write up and issue.
