### ISSUE TITLE
Refresh connection on App Mode

### ISSUE THREAD

**Issue by peterwilli** [marimo-team/marimo#2488]
### Description

When running as `marimo run <file>`, and doing something intensive with a lot of RAM, and then refreshing the page, it will spawn a completely new session, risking human error, and loading things twice..

### Suggested solution

Is it possible to get the same behaviour as in edit mode, but without showing code?

Like this:
<img width="1021" alt="Showing reconnection panel" src="https://github.com/user-attachments/assets/298a35ad-b095-4b0f-8ce2-3ab460a6715f">

**Comment by peterwilli** [comment]
Wow that's super fast! Thanks! I was just checking the source while waiting for an answer!

Uhm, the thing is the App Mode runs locally in my case. It is launched through an shell script and the user can then use the notebook as application.

In the application, I load an LLM (GGUF) and one user has refreshed the browser, causing the LLM to load twice. I was not aware of this because I assumed the edit mode was similar to run mode, minus the source code.

I'm not aware how I can persist this loading across sessions, except when I launch a HTTP API or something, which I rather avoid (I really like the simplicity it has now)

**Comment by mscolnick** [comment]
Your use-case makes a lot of sense. We can consider adding `--resumable-sessions` (or `--persist-sessions`), with some sort of timeout, to the `marimo run` CLI. 

or `--single-session` (which might be easier to implement, since then we don't need to keep track of which session belongs to who).

Implementation details aside: we may not get to this for a bit, so open to contributions; I'll add some GH labels if someone wants to pick this up.

**Comment by peterwilli** [comment]
I'm actually making it right now, I wasn't sure if you'd merge it but I'll post it as PR if done!

**Comment by mscolnick** [comment]
hell yea! thanks @peterwilli, i think it would be a great addition 🙌

**Comment by peterwilli** [comment]
Here you go! https://github.com/marimo-team/marimo/pull/2489

**Comment by peterwilli** [comment]
Closing this issue as the PR is now in progress
