### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by proItheus** [marimo-team/marimo#258]
### Description

Add a dark mode to reduce eye fatigue, especially at night.

### Suggested solution

Maybe adding a switch to toggle? I think it can be useful in both app and script mode.

### Alternative

Maybe adding theme support in the long term?

**Comment by akshayka** [comment]
Hi, thanks for the suggestion.

We have an experimental dark mode, which you can enable today. It's experimental because we have more work to do to make sure it actually looks nice. We'll take your suggestion as a "+1" to prioritize polishing this and moving it out of experimental.

To activate it, edit your `~/.marimo.toml` to include

```
[experimental]
theming = true
```

For sure, theme support in the long term would be great.

**Comment by mscolnick** [comment]
hi @proItheus - this was released in `0.1.39`. you can enable dark-mode in the Configuration Popover in the top right
