### ISSUE TITLE
Mo.ui.tables() 100 columns limit

### ISSUE THREAD

**Issue by AdrienDart** [marimo-team/marimo#2662]
### Description

Hi team,

Is there a way to increase the 100 columns limit of mo.ui.tables()? 

I just go a friendly error message to ask me to post here.

Thanks again for your work!

Adrien

### Suggested solution

Similar set options as with polars.

**Comment by AdrienDart** [comment]
I can have a lot, like 500ish. 

I'm happy to manually define the limit at the beginning of a notebook when needed. I'm not looking for summaries in that case. Maybe we can disable the summary when the number of columns is above 100 too?

**Comment by akshayka** [comment]
I believe we added this limit because the frontend used to hang when
displaying very large dataframes.

Since data is now incrementally fetched from the backend, yes it’s possible
we don’t need the limit any more. For example i think we got rid of the row
limit?

Could just keep the column limit on summaries to be safe, but otherwise try
removing it
