### ISSUE TITLE
Marimo plot does not respect altair opacity parameter

### ISSUE THREAD

**Issue by echu** [marimo-team/marimo#287]
### Describe the bug

When plotting bar charts with Altair that have an opacity parameter, the `altair_chart` UI element seems to reset the opacity parameter.

Showing the Altair chart directly displays the correct figure.

```
chart = alt.Chart(data).mark_bar(opacity=0.5).encode(
    x='x', 
    y=alt.Y('value').stack(None), 
    color="distribution")
chart = mo.ui.altair_chart(chart)
chart
```

### Version

0.1.39

**Comment by mscolnick** [comment]
hey @echu, we override the opacity since this is how we signify selection. e.g. items within the selection have opacity 1, and items outside have a smaller opacity (0.2). 

for your use case, do you just want to change the selection opacity? or do you want to keep the opacity at `0.5` all the time, regardless of selection? 

it is also possible to turn off selection completely, which will prevent `mo.ui.altair_chart` from changing your opacity

**Comment by mscolnick** [comment]
hey @echu, just wanted to bump this thread, would making the selection opacity a ratio of the opacity you pass a viable solution to your issue?

**Comment by echu** [comment]
Yeah. I think making it a ratio would be viable for me. Thank you!

I tend not to know, visually, what the alpha is (except for 1 and 0), so
making them relative would do the trick.
