### ISSUE TITLE
Usefull keyboard shortcuts

### ISSUE THREAD

**Issue by EtienneT** [marimo-team/marimo#2919]
### Description

There is several very useful keyboard shortcuts in jupyter lab, for example:

- "a" insert a cell above. 
- "b" insert a cell bellow
- "d,d" delete the currently selected cell

Those don't seem to exist in marimo and would be very useful.

### Suggested solution

Add those new shortcuts

**Comment by akshayka** [comment]
These shortcuts exist but they are different.

![Image](https://github.com/user-attachments/assets/d5a7bf4f-7963-4912-aa6e-8f45e7b55305)

Deleting a cell in marimo is more destructive than deleting one in Jupyter, since marimo deletes variables in memory. This makes your code reproducible, but it also means that accidentally deleting a cell is not a nice thing. Our deletion shortcuts require the cell code to be empty before kicking in -- backspace or `dd` if vim keymaps are enabled.

These are also remappable.

Jupyter/JupyterLab have a modal editor, with different manipulation shortcuts depending on whether a cell is focused. For me and others I know, at least, this led to accidentally inputting a bunch of shortcuts when all I wanted to do was type text (I thought a cell was focused but wasn't and accidentally created a cell, accidentally deleted one, accidentally converted to markdown ...), garbling what I saw on screen. I felt this was a very poor user experience, so I am not planning to add modal editing soon.

**Comment by EtienneT** [comment]
Thank you for the precisions!
