### ISSUE TITLE
Acknowledge Pluto.jl in the website

### ISSUE THREAD

**Issue by juliohm** [marimo-team/marimo#2937]
### Documentation is

- [x] Missing
- [ ] Outdated
- [ ] Confusing
- [ ] Not sure?

### Explain in Detail

I came across this project today and was really disappointed to see that Marimo is a Ctrl+C / Ctrl+V of Pluto.jl in Julia, and yet there is not a decent acknowledgement in the website.

Can you please acknowledge your source of inspiration more explicitly so that people at least have a chance to learn about Pluto.jl? A tiny link in the end of the README.md doesn't do it justice.

I am not involved with Pluto.jl development, but I am active open-source contributor and would be really pissed off if another project copied all my ideas without extensive acknowledgement.

### Your Suggestion for Changes

Acknowledge Pluto.jl with more emphasis. Something like "Marimo is a port of Pluto.jl from Julia to Python" could at least educate people about the existence of the Julia project. They deserve more credit!

**Comment by mscolnick** [comment]
I am sorry you feel this way. I am one of the maintainers of marimo (have written a lot of the code) and have to say I have never used `Pluto.jl`, so it's hardly a Ctrl+C / Ctrl+V.

@akshayka did have the original vision, which he mentions is inspired by Pluto in the README, among other things like Observable. If I understand correctly, Pluto was also inspired by Observable (shows in their README, but not their website).

**Comment by juliohm** [comment]
Even the examples in the gallery are inspired by the examples in the Pluto website:

# Pluto

![Image](https://github.com/user-attachments/assets/36475366-0cca-4c38-bb15-8d43e4d54c73)

# Marimo

![Image](https://github.com/user-attachments/assets/6eb97fc6-c762-4356-939b-c3c844c10931)

I really think that more credit is necessary.

**Comment by mscolnick** [comment]
That example is from our community gallery and was written by a member of the marimo community, if you clicked the example, you would see the attribution to both Grant and Pluto.

![Image](https://github.com/user-attachments/assets/992a8398-134e-4e33-8e5b-dab8e194b23c)

**Comment by juliohm** [comment]
Hi @mscolnick , thank you for clarifying the situation with the example in the gallery.

Still, something is really off in terms of acknowledgements.

**Comment by akshayka** [comment]
Hey @juliohm . I'm Akshay; like Myles said, I had the original vision for making marimo.

You might not be involved in Pluto.jl. But I have in fact corresponded with @fonsp, Pluto's creator, and Paul Berg, another Pluto maintainer.

![Image](https://github.com/user-attachments/assets/b8d01586-4c62-4dfe-8519-1e56c6bcac61)

You'll notice the repo is linked in the message. They have responded enthusiastically in turn.

But marimo is hardly just "a port" of Pluto.jl to Python. It also remixes ideas from Streamlit (deploying marimo notebooks as read-only apps) from Observable (importable cells, which last I checked is not possible in Julia due to its flat file format), and from other projects.

marimo also has many ideas that we have not seen in other projects, including statically joining graphs across multiple languages (Python and SQL), notebook-level composition that embeds kernels inside other kernels, and Nix-inspired persistent caching (contributed by a community member). Many of our contributors have brought their own ideas to marimo, and have never used or seen Pluto.jl.

I love Pluto.jl; it's a phenomenal project, crafted with so much love and care, and it is truly an inspiration. We highlight our love for Pluto in the README, in forum posts, on social media, and in podcasts.

If you happen to drop in, @fonsp: thanks again for everything! ❤️

P.S. We weren't aware that the seam carving example was on Pluto's site. We just thought that it was a very compelling example.

**Comment by liquidcarbon** [comment]
Chuck Norris can Ctrl+C from one language and Ctrl+V into another

**Comment by juliohm** [comment]
Hi Akshay, I'm not saying that Marimo doesn't have other features developed
after Pluto.jl. I'm saying that all the features highligted in the website
are pretty much Pluto.jl's.

The fact that Pluto is such an inspiration and yet is not acknowledged on
the website creates the wrong message that Marimo is the project that led
those innovations.

Happy you exchanged words with Pluto creators. I still don't think you are
doing it justice hiding it from the website.

Em sex., 22 de nov. de 2024, 19:31, Alexander Kislukhin <
***@***.***> escreveu:

**Comment by akshayka** [comment]
>  I'm not saying that Marimo doesn't have other features developed after Pluto.jl

Well, that's not at all what you said when you said that marimo is a `Ctrl+C / Ctrl+V` of Pluto.jl — which is a comment that is simply not true, and putting aside Myles and me (the only two project maintainers), is a really unkind thing to say to our community of contributors.

**Comment by juliohm** [comment]
Yes, sorry for the `Ctrl+C / Ctrl+V`, but the Marimo website really made me feel bad for the Pluto devs. Try to be in their position, and imagine someone selling Marimo's successful ideas to a larger community, getting all the attention and funding. It doesn't feel fair. Even if I was a core Pluto dev, I wouldn't feel comfortable opening an issue here claiming acknowledgement. That is kind of humiliating. In academic settings, we take acknowledgements very seriously, that is where I am coming from.

**Comment by akshayka** [comment]
Thanks for the apology.

marimo is not a "port of Pluto.jl". It is part of a family of [next-generation computational notebooks](https://www.nature.com/articles/d41586-021-01174-w), including [ObservableHQ](https://observablehq.com/documentation/notebooks/), [Pluto.jl](https://plutojl.org/), [Livebook](https://livebook.dev/), [Starboard](https://starboard.gg/), and likely others I've missed. These are all different turns on the same idea: that interactive computing should be powered by DAGs, an idea dating back at least to the spreadsheet.

Just as Pluto.jl was inspired by ObservableHQ, marimo was inspired by Pluto.jl (and other projects). Just as Pluto.jl calls out their inspiration in their README (but not website), we do, too, in our README, social posts, podcasts, and talks. If we were to ever write an academic paper about marimo (I am [no stranger](https://scholar.google.com/citations?hl=en&user=luReW0QAAAAJ) to academia), we would certainly acknowledge Pluto.jl there, too.
