### ISSUE TITLE
marimo export ipynb should include outputs, cell order, and other metadata

### ISSUE THREAD

**Issue by mscolnick** [marimo-team/marimo#2960]
### Description

marimo export ipynb should support `--include-outputs`.

We should also include more metadata to be more easily integrated with tools that can leverage this.

### Suggested solution

`marimo export ipynb notebook.py -o notebook.ipynb --include-outputs`

This will run marimo through once and include their HTML outputs. We may need to include an additional cell that contains css/js links that by default will be fetched from a cdn.

**Comment by dmadisetti** [comment]
Responding to #2961 in this issue because it seems more relevant.

---

@akshayka @liquidcarbon `.qmd` is the runnable form, but Quarto can render to markdown with full outputs (the extension would just be `.md`), jupyter with outputs, and to PDF.

I do think that providing this export is reasonable, since someone is going to want to do it for whatever esoteric workflow they have.

This is also an opportunity to tag the outputs with a "generated in marimo" banner, for potential brand promotion/ indication that the exported notebook might not work out of the box
