### ISSUE TITLE
auto-download for marimo ipynb

### ISSUE THREAD

**Issue by mscolnick** [marimo-team/marimo#2961]
### Description

We already support auto-exporting HTML. We should add auto-exporting for ipynb in top-down order with the outputs, so that users can commit these files to github and view them natively.

### Suggested solution

An additional option in this dropdown

![Image](https://github.com/user-attachments/assets/61a37e98-0153-46e9-8873-0eb9d6f1899a)

**Comment by liquidcarbon** [comment]
How do you feel about supporting Quarto?

Instead of generating a complicated JSON, you could be generating a git-friendly `.qmd` markdown file.  Much simpler to compose and maintain.  I can help with that.

Quarto then can take care of IPYNB generation - `.ipynb <-- quarto convert --> .qmd` (it works via pandoc).  QMD files can also run directly like notebooks via VS Code plugin.

Either in addition to this, or as an alternative, how about:
1) set up an API for generating `.qmd` files; it needs a frontmatter template (YAML)
2) give an option for also saving `.ipynb` via `quarto convert` (also in file manager)

**Comment by liquidcarbon** [comment]
Ditto for #2960 - it's already solved in Quarto

**Comment by akshayka** [comment]
A community member (@dmadisetti) has developed an experimental `Quarto` extension but it hasn't gotten much use yet I believe: https://github.com/dmadisetti/quarto-marimo

The main point of supporting `ipynb` is two-fold:

1. View notebook with outputs on GitHub (`qmd` doesn't render on GitHub I believe).
2. Compatibility with ecosystem of tooling built around `ipynb` files (such as static site generation and inclusion in docs), to make it easier for existing Jupyter users to adopt marimo. 

In this case the point isn't to be git-friendly. If I understand correctly, `qmd` files don't include outputs like plots, etc, making them git-friendly but not suitable for output snapshots.

**Comment by liquidcarbon** [comment]
Check out #2994
