### ISSUE TITLE
Showing Pandas DataFrame crashes marimo

### ISSUE THREAD

**Issue by noeleont** [marimo-team/marimo#339]
### Describe the bug

When I display a DataFrame with a lot of rows, e.g. [California housing dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html) directly, marimo is getting really unresponsive. 

I would expect to add a pagination or show the first and last few rows (like Jupyter does). 

If you can point me in the right direction, I'm happy to help!

### Version

0.1.47

### Code to reproduce

```python
import marimo
 
__generated_with = "0.1.47"
app = marimo.App()
 
 
@app.cell
def __():
    from sklearn.datasets import fetch_california_housing
    return fetch_california_housing,
 
 
@app.cell
def __(fetch_california_housing):
    data = fetch_california_housing(as_frame=True)
    return data,
 
 
@app.cell
def __(data):
    data.get("data")
    return
```

**Comment by akshayka** [comment]
@noeleont, thanks for reporting!

The code for how dataframes are formatted is here: https://github.com/marimo-team/marimo/blob/main/marimo/_output/formatters/pandas_formatters.py#L21-L27

You'll see we just call `df.to_html()`.

I like your suggestion to truncate or  show the head/tail only for sufficiently large dataframes. If you'd like you're more than welcome to make a PR, otherwise I'm happy to do it!

**Comment by noeleont** [comment]
@akshayka, thanks for your fast response :)

**Comment by akshayka** [comment]
> @akshayka, thanks for your fast response :)

No problem! Really appreciate the bug report.

PR #341 implements showing just the first and last few rows of dataframes, similar to what Jupyter does. Will release it later today (unless you have any objections)!

**Comment by akshayka** [comment]
@noeleont, `v0.1.49` was just released including the fix. Feel free to re-open if you still have an issue!
