### ISSUE TITLE
Have an option in the settings to also export to html (without prompting) when saving or auto saving.

### ISSUE THREAD

**Issue by roberthobblebottom** [marimo-team/marimo#718]
### Description

Sometime the outputs of the cells can be important and be overlooked. and when the marimo closes, the output is gone.

### Suggested solution

Have an option in the settings to also export to html (without prompting) when saving or auto saving.

### Alternative

*No response*

### Additional context

*No response*

```[tasklist]
### Tasks
```

**Comment by akshayka** [comment]
Hey @themissingCRAM -- I think that's a great idea! Thank you for the suggestion. We will do this.

**Comment by mscolnick** [comment]
@roberthobblebottom - this should be fixed by https://github.com/marimo-team/marimo/pull/1141 
We didn't want to put this setting in the UI and think the experience is better as a CLI. This was you can chose where to save this and if you need to re-redirect this to another program with `|` or `>`.

In the next release, you will be able to generate HTML from the command line with `watch`:

```bash
# prints to stdout
marimo export html notebook.py > out.html
# writes to the outfile
marimo export html notebook.py --output out.html
# writes to the outfile and watch notebook.py for changes
marimo export html notebook.py --watch --output out.html
```
