### ISSUE TITLE
The form method is not gating the submission

### ISSUE THREAD

**Issue by asbisen** [marimo-team/marimo#805]
### Describe the bug

Using form method with multiple elements does not gates on "Submit" button for submission. Change in any UIElement is reflected immediately.

### Environment

```json
{
  "marimo": "0.2.5",
  "OS": "Darwin",
  "OS Version": "23.3.0",
  "Processor": "arm",
  "Python Version": "3.12.2",
  "Binaries": {
    "Chrome": "--",
    "Node": "v21.6.2"
  },
  "Requirements": {
    "black": "24.2.0",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7",
    "starlette": "0.36.3",
    "tomlkit": "0.12.0",
    "typing_extensions": "4.9.0",
    "uvicorn": "0.27.1"
  }
}
```

### Code to reproduce

```python
import marimo as mo

mydropdown = mo.ui.dropdown(options=["A", "B", "C"], value="B")
myslider   = mo.ui.slider(start=0,stop=100,step=1,value=50)
mytext     = mo.ui.text(value="", full_width=True)

mo.md(f"""
{mydropdown}
{myslider}
{mytext}
""").batch(
    mydropdown=mydropdown,
    myslider=myslider,
    mytext=mytext
).form(show_clear_button=True)


print(f"Dropdown: {mydropdown.value} | Slider: {myslider.value} | Text: {mytext.value}")
```

**Comment by asbisen** [comment]
Makes sense so instead of individual elements, the access should be through form object (example:  `my_form.value['mydropdown']`). After making the changes to the MWE I can still not make the reactivity work when I press the "Submit" button the printed values don't change/updates. 


![Screenshot 2024-02-20 at 10 51 15 AM](https://github.com/marimo-team/marimo/assets/5142211/e959b307-9d86-45d4-8d6f-d5fbdd36d48f)

**Comment by mscolnick** [comment]
Actually, sorry I gave you the wrong snippet (hadn't fully tested it). Rather than using `f"` for replacement, you'll want to pass a normal `"""`, and we will fill the template under the hood. 

Side note: we plan to improve the ergonomics/devx here.  

```python
my_form = mo.md("""
{mydropdown}
{myslider}
{mytext}
""").batch(
    mydropdown=mydropdown,
    myslider=myslider,
    mytext=mytext
).form(show_clear_button=True)
```

[Here is a working snippet from https://marimo.app](https://marimo.app/?code=JYWwDg9gTgLgBCAhlUEBQaD6mDmBTAOzykRjwBNMB3YGACzgF44AiABgDoAmDgVhbSIwYJgmSoOAQWEAKGuXqMWAMwCuAG3UsAlBjQABIWA4BjPJrTk8yuNhnaAXGjgu4oSLDEoQEOIgDOCOiucFB4MKpQBEEANHqGwqbm6pbWtpgyPo7OriAAnuRQEGDkEFTRzD4cqsAchcWl5TLFMMAQBP6MANoskiwxrABC-awAwiwAugMAbojqqnhKw7oh%2Bf7qwFZQrpUQ1bXrm8Qy-jDIMIxsMafFjACMbFeneGD3MbPzi7xsK7l5ZAAPeAhXb7DiAmAyD4LJQjNSaaibRQAFSgC10ORcAGI4KNknA7piEHlMMpoCBRFUQOQZCw6USAN75eolMoEAC%2BjLWGy2nJCTP%2BeCBfNcdJ0HAARqQTHQZETVgUiqzyoxmUrGgQ4iEFYctqq8rriFrtS58hD9RCidoOGSoCATnQypgTOo8MhMBLVDAYO1GKj0XoFaTyUSwhEosTg3aBmqGmyYwaeUbiZaMAljGYLFYbHYfAmoyBsqs9jcwDICBB4PkCxxoXgMSEwCgCJDlCwACLqtkOOACmt1roAcljyoIg4m7J0RKbwBbMjbAGUk1Ae33bSBa3MFkPuUcoOPJ78XDO523kUKYKvq%2BvN58d4KgQepyEw5ECHpgDnMARECA8NgmGYFhsCQWdsBYJwQiMDg0QIewgA)
