### ISSUE TITLE
Indented UI inputs don't show up

### ISSUE THREAD

**Issue by metaboulie** [marimo-team/marimo#990]
### Describe the bug

<img width="760" alt="Screenshot 2024-03-22 at 21 25 14" src="https://github.com/marimo-team/marimo/assets/114637443/a8668fad-5a51-4e9f-a376-2e0443d3ac3f">

As displayed, a ui component won't show up if it's indented.

### Environment

{
  "marimo": "0.3.4",
  "OS": "Darwin",
  "OS Version": "22.3.0",
  "Processor": "arm",
  "Python Version": "3.12.0",
  "Binaries": {
    "Chrome": "123.0.6312.59",
    "Node": "v20.7.0"
  },
  "Requirements": {
    "black": "23.9.1",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7",
    "starlette": "0.36.1",
    "tomlkit": "0.12.3",
    "typing_extensions": "4.8.0",
    "uvicorn": "0.27.0"
  }
}

**Comment by akshayka** [comment]
This isn't a bug, but I can understand why it is confusing. An `if` statement in Python has no value; marimo shows the value of the last expression in the cell. Hence why you get no output.

Your workaround is the correct way to conditionally show an output in marimo, since a ternary (... `if` ... `else` ...) is an expression in Python which has a value.
